//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readings
    {
        public System.DateTime Date { get; set; }
        public string RID { get; set; }
        public Nullable<int> Degrees { get; set; }
        public Nullable<int> Humidity { get; set; }
    
        public virtual CRoom CRoom { get; set; }
    }
}
